[package]
name = "macchina"
version = "1.1.6"
authors = ["Aziz Ben Ali <ba.tahaaziz@gmail.com>", "Marvin Haschker <marvin@haschker.me>", "Uttarayan Mondal <email@uttarayan.me>"]
edition = "2018"
description = "A system information fetcher, with an emphasis on performance."
keywords = ["system", "fetch", "cli"]
repository = "https://github.com/Macchina-CLI/macchina"
license = "MIT"
readme = "README.md"
build = "build.rs"

[dependencies]
libmacchina = "2.1.5"
bytesize = "1.0.1"
clap = "2.33.3"
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
atty= "0.2.14"
colored = "2.0.0"
structopt = "0.3.23"
rand = "0.8.4"
unicode-width = "0.1.8"
lazy_static = "1.4.0"
ansi-to-tui = "0.4.0"
serde = { version = "1.0.130", features = ["derive"] }
dirs = "4.0"
toml = "0.5.8"
serde_json = "1.0.68"

[build-dependencies]
vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] }

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1

[features]
openwrt = ["libmacchina/openwrt"]
