[package]
name = "macchina"
version = "0.8.21"
authors = ["Taha Aziz Ben Ali <ba.tahaaziz@gmail.com>", "Marvin Haschker <marvin@haschker.me>"]
edition = "2018"
description = "A system information fetcher, with an emphasis on performance and minimalism."
keywords = ["system", "fetch", "cli"]
repository = "https://github.com/Macchina-CLI/macchina"
license = "MIT"
readme = "README_CARGO.md"
build = "build.rs"

[dependencies]
libmacchina = "0.4.2"
bytesize = "1.0.1"
clap = "2.33.3"
tui = { version = "0.14.0", default-features = false, features = ['crossterm'] }
atty= "0.2.14"
colored = "2.0.0"
structopt = "0.3.21"
rand = "0.8.3"
unicode-width = "0.1.8"
lazy_static = "1.4.0"
ansi-to-tui = "0.1.8"
serde = { version = "1.0.125", features = ["derive"] }
dirs = "3.0.2"
toml = "0.5.8"
serde_json = "1.0.64"

[build-dependencies]
libmacchina = "0.4.2"
bytesize = "1.0.1"
clap = "2.33.3"
tui = { version = "0.14.0", default-features = false }
structopt = "0.3.21"
rand = "0.8.3"
unicode-width = "0.1.8"
serde = { version = "1.0.125", features = ["derive"] }
dirs = "3.0.2"
toml = "0.5.8"
serde_json = "1.0.64"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1

[features]
openwrt = ["libmacchina/openwrt"]
